name: 'Clean Student Version'
description: 'Run book cleaning script and push changes'

inputs:
  token:
    description: 'token with push permissions for the repo'
    required: true

runs:
  using: "composite"
  steps:
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # install the python version needed
        
    - name: install python packages
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        
    - name: execute py cleaning script # run clean_book.py
      shell: bash
      run: python .github/workflows/clean_book.py

    - name: execute py replacement script # run replace_readme.py
      shell: bash
      run: python .github/workflows/replace_readme.py

    - name: commit files
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -a -m "cleaned books for student version" --allow-empty

    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ inputs.token }}
        branch: main 
        force: true